name: Release

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        targets: [
          {
            os: ubuntu-latest, 
            target: x86_64-unknown-linux-gnu,
            target2: x86_64-unknown-linux-gnu,
            cross: false, 
            name: linux64, 
            ext: "",
            vcpkg: "x64-linux-release",
            vcpkg2: "x64-linux-release",
            ffmpeg_url: "",
            ffmpeg_name: "ffmpeg-5.0-linux-clang-gpl-lite"
          },
          {
            os: macos-latest,
            target: x86_64-apple-darwin,
            target2: aarch64-apple-darwin,
            cross: false,
            name: mac-universal, 
            ext: "",
            vcpkg: "x64-osx-release",
            vcpkg2: "arm64-osx",
            ffmpeg_url: "",
            ffmpeg_name: "ffmpeg-5.0-macOS-gpl-lite"
          },
          {
            os: windows-2022,
            target: x86_64-pc-windows-msvc,
            target2: x86_64-pc-windows-msvc,
            cross: false,
            name: windows64, 
            ext: ".exe",
            vcpkg: "x64-windows-release",
            vcpkg2: "x64-windows-release",
            ffmpeg_url: "https://sourceforge.net/projects/avbuild/files/windows-desktop/ffmpeg-5.0-windows-desktop-clang-gpl-lite.tar.xz/download",
            ffmpeg_name: "ffmpeg-5.0-windows-desktop-clang-gpl-lite"
          }
      ]
    runs-on: ${{ matrix.targets.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.targets.target }}
      - uses: Swatinem/rust-cache@v1
        with:
          key: gf11

      - name: Add rust target
        run: rustup target add ${{ matrix.targets.target2 }}

      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: '${{ github.workspace }}/ext/vcpkg'
          vcpkgGitCommitId: 218ea21905bbad1f9648f18639563e5c80af1bc5
      
      # Download and install OpenCV
      - name: Install OpenCV and curl
        if: ${{ matrix.targets.os != 'ubuntu-latest' }}
        run: |
          vcpkg install "opencv4[core]:${{ matrix.targets.vcpkg }}"
          vcpkg install "opencv4[core]:${{ matrix.targets.vcpkg2 }}"
          vcpkg install "curl[core]:${{ matrix.targets.vcpkg }}"
          vcpkg install "opencl:${{ matrix.targets.vcpkg }}"

      # Download and install Qt
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ext/Qt
          key: QtCache-${{ runner.os }}-6.2.3
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 6.2.3
          dir: ${{ github.workspace }}/ext/
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      # Install LLVM
      - name: Cache LLVM and Clang
        if: ${{ matrix.targets.os == 'windows-2022' }}
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/llvm
          key: llvm-13.0
      - name: Install LLVM and Clang
        if: ${{ matrix.targets.os == 'windows-2022' }}
        uses: KyleMayes/install-llvm-action@v1.5.0
        with:
          version: "13.0"
          directory: ${{ runner.temp }}/llvm
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Set LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
        if: ${{ matrix.targets.os == 'windows-2022' }}

      # Download ffmpeg
      - name: Download ffmpeg
        if: ${{ matrix.targets.os == 'windows-2022' }}
        run: |
          cd ${{ github.workspace }}/ext/
          curl -L ${{ matrix.targets.ffmpeg_url }} -o ffmpeg.tar.xz
          7z x ffmpeg.tar.xz
          7z x ffmpeg.tar

      - name: Install dependencies Mac
        if: ${{ matrix.targets.os == 'macos-latest' }}
        run: |
          cd ${{ github.workspace }}/ext
          chmod +x install-deps-mac.sh
          ./install-deps-mac.sh CI

      - name: Install dependencies Linux
        if: ${{ matrix.targets.os == 'ubuntu-latest' }}
        env:
          PROJECT_DIR: ${{ github.workspace }}
          QT_DIR: ${{ env.Qt6_DIR }}
        run: |
          chmod +x ${{ github.workspace }}/ext/install-deps-linux.sh
          chmod +x ${{ github.workspace }}/_deployment/deploy-linux.sh
          ${{ github.workspace }}/_deployment/deploy-linux.sh build-docker

      - name: Build Gyroflow
        if: ${{ matrix.targets.os == 'windows-2022' }}
        env:
          CARGO_TARGET_DIR: ./target
          FFMPEG_DIR: ${{ github.workspace }}/ext/${{ matrix.targets.ffmpeg_name }}
          OPENCV_LINK_LIBS: opencv_core,opencv_calib3d,opencv_features2d,opencv_imgproc,opencv_video,opencv_flann,opencv_imgcodecs
          OPENCV_LINK_PATHS: ${{ github.workspace }}/ext/vcpkg/installed/${{ matrix.targets.vcpkg }}/lib
          OPENCV_INCLUDE_PATHS: ${{ github.workspace }}/ext/vcpkg/installed/${{ matrix.targets.vcpkg }}/include
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.targets.cross }}
          command: build
          args: --target ${{ matrix.targets.target }} --profile deploy

      - name: Build and deploy Mac
        if: ${{ matrix.targets.os == 'macos-latest' }}
        env:
          PROJECT_DIR: ${{ github.workspace }}
          QT_DIR: ${{ env.Qt6_DIR }}
          OPENCV_DIR: ${{ github.workspace }}/ext/vcpkg/installed/
          FFMPEG_DIR: ${{ github.workspace }}/ext/${{ matrix.targets.ffmpeg_name }}
        run: |
          chmod +x ${{ github.workspace }}/_deployment/deploy-macos.sh
          ${{ github.workspace }}/_deployment/deploy-macos.sh deploy-universal

      - name: Copy dist Windows
        if: ${{ matrix.targets.os == 'windows-2022' }}
        env:
          FFMPEG_DIR: ${{ github.workspace }}/ext/${{ matrix.targets.ffmpeg_name }}
        run: |
          ${{ github.workspace }}/_deployment/deploy-windows.bat ${{ github.workspace }} ${{ env.Qt6_DIR }} ${{ github.workspace }}/ext/vcpkg/installed/${{ matrix.targets.vcpkg }}/bin ${{ github.workspace }}/target/${{ matrix.targets.target }}/deploy 
          cd ${{ github.workspace }}/_deployment/_binaries/win64/
          7z a ../Gyroflow-${{ matrix.targets.name }}.zip *

      - name: Save Binaries
        uses: actions/upload-artifact@v2
        with:
          name: gyroflow
          path: _deployment/_binaries/*.*

  github_release:
    name: Create GitHub release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: gyroflow
   
      - run: ls -l

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
         files: ./*
